config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users

  resources :users do
    resources :followers_relationships
  end

  resources :followers_relationships, only: [:destroy]

  resources :posts do
    resources :likes
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/followers_relationship.rb
class FollowersRelationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  include ImageUploader::Attachment(:image)

  belongs_to :user
  has_many :comments
  has_many :likes, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
  has_many :likes, dependent: :destroy

  has_many :followers, class_name: 'FollowersRelationship', foreign_key: 'followed_id'
  has_many :followings, class_name: 'FollowersRelationship', foreign_key: 'follower_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.user = current_user

    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :body)
  end
end

app/controllers/followers_relationships_controller.rb
class FollowersRelationshipsController < ApplicationController
  def create
    followed = User.find(params[:user_id])
    @relation = FollowersRelationship.new(follower_id: current_user.id,
                                          followed_id: followed.id)

    @relation.save
    redirect_to user_path(followed)
  end

  def destroy
    @relation = FollowersRelationship.find(params[:id])

    @relation.destroy
    redirect_to user_path(@relation.followed_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :post_find
  before_action :find_like, only: [:destroy]

  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @post.likes.create(user_id: current_user.id)
    end
    redirect_to post_path(@post)
  end

  def destroy
    if !(already_liked?)
      flash[:notice] = "Cannot unlike"
    else
      @like.destroy
    end
    redirect_to post_path(@post)
  end

  private

  def post_find
    @post = Post.find(params[:post_id])
  end

  def find_like
    @like = @post.likes.find(params[:id])
  end

  def already_liked?
    Like.where(user_id: current_user.id, post_id:
    params[:post_id]).exists?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params) && @post.user_id == current_user.id
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :user_id, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @relation = @user.followers.find_by(follower: current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_relationships_helper.rb
module FollowersRelationshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaCloneRuby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <%= link_to 'Rubygram', root_path, class: 'navbar-brand' %>
          <%= link_to "New post", new_post_path %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0"></ul>
            <div class="d-flex" role="search">
              <% if current_user.nil? %>
                <%= link_to "Register",  new_user_registration_path, class: 'btn btn-outline-success' %>
                <%= link_to "Login", new_user_session_path, class: 'btn btn-outline-success' %>
              <% else %>
                <%= button_to "Log out", destroy_user_session_path, method: :delete %>
              <% end %>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <% unless current_user.nil? %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>


    <%= yield %>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/edit.html.erb
<% if current_user.id == @post.user_id %>
  <%= form_with model: @post do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </div>

    <div>
      <%= form.label :image %><br>
      <%= form.file_field :image %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
<% else %>
  <h1> You ARE NOT a creator of that post.</h1>
  <%= link_to "Return", root_path %>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="container">
    <div class="row">
      <div class="col"></div>
        <div class="col-8">
          <div class="card mb-3">
            <div class="row g-0">
              <div class="col-md-4">
                <div class="ratio" style="height:250px;overflow:hidden">
                  <% if post.image %>
                    <%= link_to post do %>
                      <%= image_tag post.image_url, class: 'embed-responsive-item img-thumbnail' %>
                    <% end %>
                  <% else %>
                    <h2>No photo :C </h2>
                  <% end %>
                </div>
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title"><%= link_to post.title, post %></h5>
                  <p class="card-text"><%= post.body %></p>
                  <p class="card-text"><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
                  <p class="card-text"><small class="text-muted"><%= post.created_at %></small></p>
                  <hr>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col"></div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col"></div>
    <div class="col">
      <h1>New Article</h1>
      <%= form_with model: @post do |form| %>
        <div>
          <%= form.label :title %><br>
          <%= form.text_field :title %>
        </div>

        <div>
          <%= form.label :body %><br>
          <%= form.text_area :body %>
        </div>

        <p>
          <%= form.hidden_field :user_id %>
        </p>

        <div>
          <%= form.file_field :image %>
        </div>

        <div>
          <%= form.submit %>
        </div>
      <% end %>
    </div>
    <div class="col"></div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col"></div>
    <div class="col-8">
      <div class="card mb-3">
        <div class="row g-0">
          <div class="col-md-6">
            <img src=<%= @post.image_url %> class="img-fluid rounded-start" alt="...">
          </div>
          <div class="col-md-6">
            <div class="card-body">
              <h5 class="card-title"><%= @post.title %></h5>
              <hr>
              <p class="card-text"><%= @post.body %></p>
              <hr>
              <p><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
              <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
              <% if pre_like %>
                <%= button_to 'Unlike', post_like_path(@post, pre_like), method: :delete %>
              <% else %>
                <%= button_to 'Like', post_likes_path(@post), method: :post %>
              <% end %>
              <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
              <hr>
            </div>

            <div class='card-body'>
              <% if ((user_signed_in?) && (current_user.id == @post.user_id)) %>
                <%= link_to "Edit", edit_post_path(@post) %>
                <%= button_to "Destroy", post_path(@post), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
              <% end %>
              <h2>Add a comment:</h2>
                <%= form_with model: [ @post, @post.comments.build ] do |form| %>
                  <p>

                  <%= current_user.email %>
                  <%= form.hidden_field :user_id %>
                  </p>
                  <p>
                  <%= form.label :body %><br>
                  <%= form.text_area :body %>
                  </p>
                  <p>
                  <%= form.submit %>
                  </p>
                <% end %>
              </div>
            </div>
          </div>
      </div>
      <div class="col"></div>
    </div>
    <div class="col"></div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col">
      Column
    </div>
    <div class="col-8">
        <div class="card mb-4">
          <div class="row g-0">
            <div class="col-md-4">
              <img src="https://i.imgur.com/710zC3Z.png" style="width:200px;height:200px;overflow:hidden" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title col-12"><%= @user.email %></h5>
                <div class="container text-center">
                  <div class="row">
                    <div class="col-4">
                      <strong><%= @user.posts.count %></strong>
                        Posts
                    </div>
                    <div class="col-4">
                      <strong><%= @user.followers.count %></strong>
                      Followers
                    </div>
                    <div class="col-4">
                      <strong><%= @user.followings.count %></strong>
                      Followed
                    </div>
                  </div>
                </div>
                  <% if @relation.present? %>
                    <%= button_to 'Unfollow', followers_relationship_path(@relation.id), method: :delete %>
                  <% else %>
                    <%= button_to 'Follow', user_followers_relationships_path(@user), method: :post %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <div class="row row-cols-1 row-cols-md-3 g-4">
            <% @user.posts.each do |post| %>
            <div class="col">
                <div class="ratio" style="width:250px;height:250px;overflow:hidden">
                <% if post.image %>
                    <%= image_tag post.image_url, class: 'embed-responsive-item img-thumbnail' %>
                <% else %>
                  <h2>No photo :C </h2>
                <% end %>
                </div>
            </div>
            <% end %>
            </div>
          </div>
          <div class="col">
            Column
          </div>
        </div>
      </div>
    </div>
  </div>
</div>